# Generated by Django 4.0 on 2021-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
