# Generated by Django 4.0 on 2021-12-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_question_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
