# Generated by Django 4.0 on 2021-12-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_schedule'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer_ids', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.question')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.score')),
            ],
        ),
    ]
